add target arg for clang
nickray/littlefs2-sys pull request #1
Opened 2020-05-29 16:40 UTC by conorpp

2020-05-29 17:52 UTC, nickray commented
When is this needed? Does this work when no TARGET is set in env?

2020-07-30 19:52 UTC, conorpp commented
It doesn't work for MacOS unless the target is set

2020-08-08 00:07 UTC, nickray requested changes

2020-08-08 00:07 UTC, nickray commented on build.rs
> +    let target = env::var("TARGET").unwrap_or("".to_string());
I think `env::var("TARGET")?` as in micro-ecc-sys should work here (TARGET is always set).

2020-08-08 00:08 UTC, nickray commented
Do you need a release here (and in micro-ecc-sys)?

2020-08-08 17:31 UTC, conorpp commented
Yeah that would be nice

2021-01-06 11:14 UTC, merged